
#Spring Data Source ?? - MySQL DB?? ?? ??

spring:
  application:
    name: todoApp
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/devdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true